#baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = 'Severiano Sisneros'
theme = 'holy'
paginate = 3

[menu]

    [[menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
        weight = 10

    [[menu.main]]
        identifier = "videos"
        name = "Videos"
        pageRef = "/videos"
        weight = 10