baseURL = "https://severiano-sisneros.github.io"
relativeURLs = true
languageCode = 'en-us'
title = "Severiano Sisneros | severiano.eth"
theme = 'archie'
paginate = 3
enableEmoji = true
# Your Disqus sortname.
disqusShortname = "severiano-sisneros-github-io"

# Content types which are excludes Disqus comments.
disableDisqusTypes = ["page"]

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
    favicon = "fav.ico"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "All posts"
        url = "/posts"
        weight = 2

    [[menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
        weight = 4
    [[menu.main]]
        name = "Tags"
        url = "/tags"
        weight = 3



[taxonomies]
    tag = "tags"
    category = "categories"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/severiano-sisneros"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/SeveSisneros"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:seve.sisneros@protonmail.com"
