#baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = 'Severiano Sisneros'
theme = 'holy'
paginate = 3

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10